### Константы и переменные в tensorflow

In [9]:
import tensorflow as tf
import numpy as np

В тензорфлоу всё построено на тензорах - многомерных матрицах. Однако тензором может быть и простое число, и вектор.

#### Константы (tf.constant). Их изменять нельзя

In [3]:
a = tf.constant(2)
print(a)

tf.Tensor(2, shape=(), dtype=int32)


In [5]:
a = tf.constant(2, shape=(1, 1))
print(a)

tf.Tensor([[2]], shape=(1, 1), dtype=int32)


In [6]:
b = tf.constant([1, 2, 3, 4])
print(b)

tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)


In [7]:
c = tf.constant([[1, 2],
                [3, 4],
                [5, 6]], dtype=tf.float16)
print(c)

tf.Tensor(
[[1. 2.]
 [3. 4.]
 [5. 6.]], shape=(3, 2), dtype=float16)


Изменить тип данных тензора - tf.cast

In [8]:
a2 = tf.cast(a, dtype=tf.float32)
print(a2)

tf.Tensor([[2.]], shape=(1, 1), dtype=float32)


#### Переменные (tf.Variable). Их значения можно менять

In [17]:
v1 = tf.Variable(-1.2)
v2 = tf.Variable([2, 3, 4], dtype=tf.float16)
v3 = tf.Variable(b)
print(v1, v2, v3, sep='\n')

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=-1.2>
<tf.Variable 'Variable:0' shape=(3,) dtype=float16, numpy=array([2., 3., 4.], dtype=float16)>
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([1, 2, 3, 4])>


Метод assign позволяет задавать новое значение для тензора. assign_add - складывает значения, assign_sub - вычитает значенияиз значений тензора.

In [18]:
v1.assign(3)
v2.assign_add([1, 1, 1])
v3.assign_sub([1, 1, 1, 1])
print(v1, v2, v3, sep='\n')

<tf.Variable 'Variable:0' shape=() dtype=float32, numpy=3.0>
<tf.Variable 'Variable:0' shape=(3,) dtype=float16, numpy=array([3., 4., 5.], dtype=float16)>
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([0, 1, 2, 3])>


assign применять предпочтительнее, чем задавать новый тензор с тем же именем

Посмотреть размерность массива

In [19]:
v3.shape

TensorShape([4])

#### Индексы и срезы

Аналогично numpy

In [21]:
val_0 = v3[0]
val_12 = v3[1:3]
print(v3, val_0, val_12, sep='\n')

<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([0, 1, 2, 3])>
tf.Tensor(0, shape=(), dtype=int32)
tf.Tensor([1 2], shape=(2,), dtype=int32)


Важно знать, что переменные val_0 val_12 являются лишь ссылками на соответствующие элементы в массиве. Их изменить нельзя, но через них можно изменить элементы массива

In [25]:
val_0.assign(10)
print(val_0, v3, sep='\n')

tf.Tensor(0, shape=(), dtype=int32)
<tf.Variable 'Variable:0' shape=(4,) dtype=int32, numpy=array([10,  1,  2,  3])>


Выборка отдельных элементов массива (tf.gather)

In [26]:
x = tf.constant(range(10)) + 5
print(x)

tf.Tensor([ 5  6  7  8  9 10 11 12 13 14], shape=(10,), dtype=int32)


In [38]:
tf.gather(x, [2, 4])

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 9])>

Для матриц индексирование аналогично тому, как это делается в numpy

In [52]:
a = tf.constant([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])
a[1, 2].numpy()

6

In [54]:
a[0].numpy()

array([1, 2, 3])

In [55]:
a[:, 2].numpy()

array([3, 6, 9])

#### Преобразовать размерность матрицы (tf.reshape)

In [50]:
tf.reshape(a, [9])

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9])>

#### Транспонировать матрицу (tf.transpose)

In [59]:
a_T = tf.transpose(a, perm=[1, 0])
print(a, a_T, sep='\n\n')

tf.Tensor(
[[1 2 3]
 [4 5 6]
 [7 8 9]], shape=(3, 3), dtype=int32)

tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int32)
