In [5]:
import tensorflow as tf
import numpy as np
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

### Функции автозаполнения

#### Создать матрицу, заполненную нулями: tf.zeros

In [6]:
a = tf.zeros((3, 3))
a

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

#### Создать матрицу, заполенную единицами: tf.ones

In [7]:
b = tf.ones((5, 3))
print(b)

tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]], shape=(5, 3), dtype=float32)


#### Создать матрицу, заполненную единицами, на основе формы другой матрицы: tf.ones_like

In [9]:
c = tf.ones_like(a)
c

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [26]:
arr = np.array([[1, 2], [3, 4]], dtype=int)
ff = tf.ones_like(arr)
ff

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 1],
       [1, 1]])>

#### Создать матрицу, заполненную нулями, на основе формы другой матрицы: tf.zeros_like

In [10]:
d = tf.zeros_like(b)
d

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

#### Создать матрицу с единицами на главной диагонали: tf.eye

In [13]:
f = tf.eye(3)
f

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)>

In [17]:
g = tf.eye(3, 2)
g

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[1., 0.],
       [0., 1.],
       [0., 0.]], dtype=float32)>

#### Создание копии тензоров с сохранением их значений: tf.identity

In [20]:
h = tf.identity(d)
h

<tf.Tensor: shape=(5, 3), dtype=float32, numpy=
array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)>

#### Заполнить матрицу заданной формы заданным значением: tf.fill

In [21]:
i = tf.fill((2, 3,), -1)
i

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[-1, -1, -1],
       [-1, -1, -1]])>

#### Создание тензора из диапазона значений с заданным шагом: tf.range

In [22]:
j = tf.range(1, 3, 0.2)
j

<tf.Tensor: shape=(10,), dtype=float32, numpy=
array([1.       , 1.2      , 1.4000001, 1.6000001, 1.8000002, 2.0000002,
       2.2000003, 2.4000003, 2.6000004, 2.8000004], dtype=float32)>

### Генерация случайных чисел

#### Создать тензор и заполнить его значениями по нормальному закону распределения: tf.random.normal

In [27]:
a = tf.random.normal((2, 4), 0, 0.1) # 0 - мат ожидание распределения, 0.1 - стандартное отклонение
a

<tf.Tensor: shape=(2, 4), dtype=float32, numpy=
array([[-0.00159768, -0.12243473, -0.12319896, -0.11507231],
       [-0.04225143,  0.07537443, -0.03738357, -0.07111195]],
      dtype=float32)>

#### То же, только значения величин в диапазоне +-2сигма (ст. откл): tf.random.truncated_normal

In [35]:
c = tf.random.truncated_normal((1, 5), -1, 0.1) # -1 - мат ожидание распределения, 0.1 - стандартное отклонение
c

<tf.Tensor: shape=(1, 5), dtype=float32, numpy=
array([[-0.9596912 , -1.1088021 , -1.0063095 , -0.86634433, -1.0166903 ]],
      dtype=float32)>

#### Создать тензор и заполнить его значениями по равномерному закону распределения: tf.random.uniform

In [31]:
b = tf.random.uniform((3, 3), -1, 1) # 0 - мат ожидание распределения, -1 и 1 - границы распределения
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3230784 ,  0.83462286, -0.7356303 ],
       [-0.78320456,  0.5948124 , -0.5494201 ],
       [ 0.5267477 , -0.8279033 ,  0.65729403]], dtype=float32)>

#### Установить значение зерна генератора случайных чисел (для воспроизведения одних и тех же значений величин): tf.random.set_seed

In [37]:
tf.random.set_seed(1)

In [38]:
tf.random.truncated_normal((1, 7), 3, 1) #тут одинаково

<tf.Tensor: shape=(1, 7), dtype=float32, numpy=
array([[1.8987797, 4.5457516, 3.383644 , 2.1203423, 4.40552  , 3.379859 ,
        3.3629978]], dtype=float32)>

In [41]:
tf.random.set_seed(1)
tf.random.truncated_normal((1, 7), 3, 1) # и тут одинаково!

<tf.Tensor: shape=(1, 7), dtype=float32, numpy=
array([[1.8987797, 4.5457516, 3.383644 , 2.1203423, 4.40552  , 3.379859 ,
        3.3629978]], dtype=float32)>

#### Перемешать значения в матрице относительно горизонтальной оси (перемешать строки): tf.random.shuffle

In [42]:
b

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.3230784 ,  0.83462286, -0.7356303 ],
       [-0.78320456,  0.5948124 , -0.5494201 ],
       [ 0.5267477 , -0.8279033 ,  0.65729403]], dtype=float32)>

In [43]:
b1 = tf.random.shuffle(b)
b1

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[ 0.5267477 , -0.8279033 ,  0.65729403],
       [-0.78320456,  0.5948124 , -0.5494201 ],
       [ 0.3230784 ,  0.83462286, -0.7356303 ]], dtype=float32)>

In [44]:
tf.random.shuffle

### Математические операции

#### Сложение: tf.add

In [45]:
a = tf.constant([1, 2, 3])
b = tf.constant([2, 3, 4])

In [106]:
tf.add(a, b) # тип данных двух тензоров должен быть одинаковым!

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7])>

In [47]:
a + b #аналог

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 5, 7])>

#### Вычитание: tf.subtract

In [48]:
tf.subtract(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1, -1, -1])>

In [49]:
a - b # аналог

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([-1, -1, -1])>

#### Деление: tf.divide

In [50]:
tf.divide(b, a)

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.        , 1.5       , 1.33333333])>

In [51]:
b / a

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([2.        , 1.5       , 1.33333333])>

In [52]:
b // a

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([2, 1, 1])>

#### Умножение: tf.multiply

In [53]:
tf.multiply(a, b)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  6, 12])>

In [54]:
a * b

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 2,  6, 12])>

#### Возведение в степень

In [55]:
a ** 2

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

In [91]:
tf.square(a) # в квадрат

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([1, 4, 9])>

#### Векторное внешнее умножение: tf.tensordot(a, b, axes=0)

In [56]:
a = tf.constant([1, 2, 3])
b = tf.constant([2, 3, 4])

In [57]:
tf.tensordot(a, b, axes=0)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])>

#### Векторное внутреннее умножение: tf.tensordot(a, b, axes=1)

In [58]:
tf.tensordot(a, b, axes=1) # 1*2 + 2*3 + 3*4

<tf.Tensor: shape=(), dtype=int32, numpy=20>

#### Умножение матриц: tf.matmul

In [73]:
a1 = tf.constant(tf.range(1, 10), shape=(3, 3))
b1 = tf.constant(tf.range(5, 14), shape=(3, 3))
print(a1.numpy(), b1.numpy(), sep='\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


In [74]:
tf.matmul(a1, b1) # 1 строка 1-й матрицы * 1 столбец 2-й матрицы и т.д.

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])>

In [75]:
a1 @ b1 # аналог

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 54,  60,  66],
       [126, 141, 156],
       [198, 222, 246]])>

#### Сумма всех  элементов матрицы: tf.reduce_sum

In [77]:
n = tf.tensordot(a, b, axes=0)
n.numpy()

array([[ 2,  3,  4],
       [ 4,  6,  8],
       [ 6,  9, 12]])

In [78]:
tf.reduce_sum(n)

<tf.Tensor: shape=(), dtype=int32, numpy=54>

In [82]:
tf.reduce_sum(n, axis=[0, 1]) # аналог

<tf.Tensor: shape=(), dtype=int32, numpy=54>

#### Сумма элементов матрицы по столбцам

In [80]:
tf.reduce_sum(n, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([12, 18, 24])>

#### Сумма элементов матрицы по строкам

In [81]:
tf.reduce_sum(n, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([ 9, 18, 27])>

#### Среднее арифметическое значений в матрице: tf.reduce_mean

In [83]:
tf.reduce_mean(n)

<tf.Tensor: shape=(), dtype=int32, numpy=6>

In [85]:
tf.reduce_mean(n, axis=0)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([4, 6, 8])>

In [86]:
tf.reduce_mean(n, axis=1)

<tf.Tensor: shape=(3,), dtype=int32, numpy=array([3, 6, 9])>

#### Минимум и максимум в матрице: tf.reduce_min, tf.reduce_max

In [87]:
tf.reduce_min(n)

<tf.Tensor: shape=(), dtype=int32, numpy=2>

In [88]:
tf.reduce_max(n)

<tf.Tensor: shape=(), dtype=int32, numpy=12>

#### Произведение всех элементов матрицы между собой: tf.reduce_prod

In [89]:
tf.reduce_prod(n)

<tf.Tensor: shape=(), dtype=int32, numpy=2985984>

#### Квадратный корень (только для матриц с вещественными числами): tf.sqrt

In [92]:
tf.sqrt(tf.cast(a, dtype=tf.float32)) # значения вектора предварительно преобразуются в вещественный тип

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1.       , 1.4142135, 1.7320508], dtype=float32)>

#### Тригонометрические функции: tf.sin tf.cos и т.д.

In [98]:
tf.sin(tf.range(-3.14, 3.14, 1)) #аргумент должен состоять из вещественных или комплексных чисел

<tf.Tensor: shape=(7,), dtype=float32, numpy=
array([-0.00159255, -0.84233034, -0.90863353, -0.13954322,  0.7578425 ,
        0.9584713 ,  0.27788603], dtype=float32)>

In [99]:
tf.cos(0.5)

<tf.Tensor: shape=(), dtype=float32, numpy=0.87758255>

In [104]:
aa = tf.constant(tf.range(1, 10), shape=(3, 3))
bb = tf.eye(3, dtype=tf.int32)
aa, bb

(<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])>,
 <tf.Tensor: shape=(3, 3), dtype=int32, numpy=
 array([[1, 0, 0],
        [0, 1, 0],
        [0, 0, 1]])>)